Repository googleinterns/noms, pull requests merged in 2020-08, with the labels that each got.

#27 Add File Hierarchy
  src/main/webapp/about.html
  src/main/webapp/assets/css/feedStyle.css
  src/main/webapp/assets/css/indexStyle.css
  src/main/webapp/assets/css/mainStyle.css
  src/main/webapp/assets/js/feedScript.js
  src/main/webapp/assets/js/indexScript.js
  src/main/webapp/assets/js/mainScript.js
  src/main/webapp/assets/svg/bobaemoji.svg
  src/main/webapp/assets/svg/burgeremoji.svg
  src/main/webapp/assets/svg/greymarker.svg
  src/main/webapp/assets/svg/pizzaemoji.svg
  src/main/webapp/assets/svg/redmarker.svg
  src/main/webapp/assets/svg/spoofmap.svg
  src/main/webapp/contact.html
  src/main/webapp/find-events.html
  src/main/webapp/index.html
  src/main/webapp/sign-up.html
Labels: refactor

#29 Setup Email Notifications
  .gitignore
  pom.xml
  src/main/java/com/google/sps/api/GmailAPI.java
  src/main/java/com/google/sps/api/GmailConfiguration.java
  src/main/webapp/about.html
  src/main/webapp/assets/bobaemoji.svg
  src/main/webapp/assets/burgeremoji.svg
  src/main/webapp/assets/feedScript.js
  src/main/webapp/assets/feedStyle.css
  src/main/webapp/assets/greymarker.svg
  src/main/webapp/assets/indexScript.js
  src/main/webapp/assets/indexStyle.css
  src/main/webapp/assets/mainScript.js
  src/main/webapp/assets/mainStyle.css
  src/main/webapp/assets/pizzaemoji.svg
  src/main/webapp/assets/redmarker.svg
  src/main/webapp/assets/spoofmap.svg
  src/main/webapp/contact.html
  src/main/webapp/find-events.html
  src/main/webapp/index.html
  src/main/webapp/sign-up.html
Labels: enhancement, prototype

#39 Revert "Setup Email Notifications"
  .gitignore
  pom.xml
  src/main/java/com/google/sps/api/GmailAPI.java
  src/main/java/com/google/sps/api/GmailConfiguration.java
  src/main/webapp/about.html
  src/main/webapp/assets/css/feedStyle.css
  src/main/webapp/assets/css/indexStyle.css
  src/main/webapp/assets/css/mainStyle.css
  src/main/webapp/assets/js/feedScript.js
  src/main/webapp/assets/js/indexScript.js
  src/main/webapp/assets/js/mainScript.js
  src/main/webapp/assets/svg/bobaemoji.svg
  src/main/webapp/assets/svg/burgeremoji.svg
  src/main/webapp/assets/svg/greymarker.svg
  src/main/webapp/assets/svg/pizzaemoji.svg
  src/main/webapp/assets/svg/redmarker.svg
  src/main/webapp/assets/svg/spoofmap.svg
  src/main/webapp/contact.html
  src/main/webapp/find-events.html
  src/main/webapp/index.html
  src/main/webapp/sign-up.html
Labels: bug

#36 Change dropdown icon, make title a link, and improve keyboard accessibility
  src/main/webapp/about.html
  src/main/webapp/assets/css/indexStyle.css
  src/main/webapp/assets/css/mainStyle.css
  src/main/webapp/contact.html
  src/main/webapp/find-events.html
  src/main/webapp/index.html
  src/main/webapp/sign-up.html
Labels: frontend, refactor

#40 Fix Odd Scrolling for Navbar on Smaller Devices
  src/main/webapp/assets/css/mainStyle.css
Labels: frontend

#38 Increase map fault tolerance and improve user experience
  src/main/webapp/assets/css/feedStyle.css
  src/main/webapp/assets/css/indexStyle.css
  src/main/webapp/assets/css/mainStyle.css
  src/main/webapp/assets/js/feedScript.js
  src/main/webapp/find-events.html
  src/main/webapp/index.html
Labels: enhancement, frontend

#43 Enhance User Experience with Input Form and Email Notifications
  .gitignore
  pom.xml
  src/main/java/com/google/sps/api/GmailAPI.java
  src/main/java/com/google/sps/api/GmailConfiguration.java
  src/main/java/com/google/sps/data/Email.java
  src/main/java/com/google/sps/servlets/UserDataServlet.java
  src/main/webapp/sign-up.html
Labels: refactor

#46 Add Secret Manager for Email Credentials
  .gitignore
  src/main/java/com/google/sps/api/GmailAPI.java
Labels: refactor

#49 Adds the Backend for Posts
  pom.xml
  src/main/java/com/google/sps/servlets/Post.java
  src/main/java/com/google/sps/servlets/PostDataServlet.java
  src/main/webapp/assets/css/feedStyle.css
  src/main/webapp/assets/js/feedScript.js
  src/main/webapp/find-events.html
Labels: backend

#50 Add JavaScript unit testing using Mocha, Chai
  .gitignore
  src/main/webapp/assets/js/feedScript.js
  src/main/webapp/assets/js/tests/README.md
  src/main/webapp/assets/js/tests/feedScript.test.js
  src/main/webapp/assets/js/tests/feedScript.testrunner.html
  src/main/webapp/assets/js/tests/package-lock.json
  src/main/webapp/assets/js/tests/package.json
Labels: documentation, testing

#59 Fix +/- buttons on map and styling issues; clean up code.
  src/main/webapp/assets/css/feedStyle.css
  src/main/webapp/assets/js/feedScript.js
Labels: backend, bug, frontend, refactor

#58 Fixes the Year Value
  src/main/java/com/google/sps/servlets/Post.java
  src/main/webapp/assets/css/feedStyle.css
  src/main/webapp/find-events.html
Labels: backend, bug, frontend, refactor

#64 Adds Accessibility to Creating and Viewing Posts
  src/main/webapp/assets/css/feedStyle.css
  src/main/webapp/assets/css/mainStyle.css
  src/main/webapp/assets/js/feedScript.js
  src/main/webapp/find-events.html
Labels: accessibility, frontend

#70 Limit Accessibility of Post Class Members
  src/main/java/com/google/sps/servlets/Post.java
Labels: backend, refactor

#65 Create Basic Contact Page
  src/main/webapp/assets/css/contactStyle.css
  src/main/webapp/assets/css/mainStyle.css
  src/main/webapp/assets/css/signUpStyle.css
  src/main/webapp/assets/jpeg/areeta.jpeg
  src/main/webapp/assets/jpeg/melanie.jpeg
  src/main/webapp/assets/jpeg/uma.jpeg
  src/main/webapp/assets/svg/github.svg
  src/main/webapp/assets/svg/linkedin.svg
  src/main/webapp/contact.html
  src/main/webapp/sign-up.html
Labels: enhancement

#60 Add Welcome and New Post Emails for Users
  pom.xml
  src/main/java/com/google/sps/api/GmailConfiguration.java
  src/main/java/com/google/sps/data/Email.java
  src/main/java/com/google/sps/data/Post.java
  src/main/java/com/google/sps/servlets/PostDataServlet.java
  src/main/java/com/google/sps/servlets/UserDataServlet.java
  src/main/webapp/assets/html_templates/NewPost.html
  src/main/webapp/assets/html_templates/WelcomeEmail.html
  src/main/webapp/assets/svg/noodleemoji.svg
Labels: enhancement

#72 Fixes Modal Text Inputs
  src/main/webapp/assets/css/feedStyle.css
  src/main/webapp/assets/css/mainStyle.css
Labels: bug, frontend

#73 Add live maps to landing/contact page + reprompt user when given bad addresses
  .gitignore
  src/main/webapp/assets/college-locations.json
  src/main/webapp/assets/css/contactStyle.css
  src/main/webapp/assets/css/feedStyle.css
  src/main/webapp/assets/css/indexStyle.css
  src/main/webapp/assets/js/contactScript.js
  src/main/webapp/assets/js/feedScript.js
  src/main/webapp/assets/js/indexScript.js
  src/main/webapp/assets/js/mainScript.js
  src/main/webapp/assets/js/tests/feedScript.test.js
  src/main/webapp/assets/js/tests/indexScript.test.js
  src/main/webapp/assets/js/tests/indexScript.testrunner.html
  src/main/webapp/contact.html
  src/main/webapp/index.html
Labels: backend, enhancement, frontend, testing

#77 Add About page and update landing page map style
  src/main/webapp/about.html
  src/main/webapp/assets/css/aboutStyle.css
  src/main/webapp/assets/css/contactStyle.css
  src/main/webapp/assets/css/indexStyle.css
  src/main/webapp/assets/favicon.ico
  src/main/webapp/assets/svg/coin.svg
  src/main/webapp/assets/svg/environment.svg
  src/main/webapp/assets/svg/heartperson.svg
  src/main/webapp/contact.html
  src/main/webapp/find-events.html
  src/main/webapp/index.html
  src/main/webapp/sign-up.html
Labels: accessibility, enhancement, frontend, refactor

#76 Writes Tests for Post Class
  pom.xml
  src/main/java/com/google/sps/data/Post.java
  src/test/java/com/google/sps/PostTest.java
Labels: backend, testing

#80 Validates the Modal Inputs
  src/main/webapp/assets/css/feedStyle.css
  src/main/webapp/assets/js/feedScript.js
  src/main/webapp/contact.html
  src/main/webapp/find-events.html
Labels: bug, frontend, refactor

#83 Fixes Modal Time Errors
  src/main/java/com/google/sps/data/Post.java
  src/main/webapp/assets/js/feedScript.js
  src/test/java/com/google/sps/PostTest.java
Labels: bug

#85 Add filtering functionality to find-events page
  src/main/webapp/assets/css/feedStyle.css
  src/main/webapp/assets/css/mainStyle.css
  src/main/webapp/assets/js/feedScript.js
  src/main/webapp/assets/js/indexScript.js
  src/main/webapp/assets/js/tests/feedScript.test.js
  src/main/webapp/contact.html
  src/main/webapp/find-events.html
Labels: backend, enhancement, frontend, testing

#93 Update README.md
  README.md
  src/main/webapp/assets/css/contactStyle.css
  src/main/webapp/contact.html
Labels: documentation

#95 Add Manual Validation for Email Form
  src/main/webapp/assets/css/signUpStyle.css
  src/main/webapp/assets/js/signUpScript.js
  src/main/webapp/sign-up.html
Labels: enhancement, frontend

#96 Add server-side input validation and improve user experience
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/main.yml
  .github/workflows/test.yml
  README.md
  pom.xml
  src/main/java/com/google/sps/data/InputPattern.java
  src/main/java/com/google/sps/data/Post.java
  src/main/java/com/google/sps/servlets/PostDataServlet.java
  src/main/java/com/google/sps/servlets/UserDataServlet.java
  src/main/webapp/assets/css/feedStyle.css
  src/main/webapp/assets/js/feedScript.js
  src/main/webapp/assets/js/indexScript.js
  src/main/webapp/assets/js/signUpScript.js
  src/main/webapp/find-events.html
  src/test/java/com/google/sps/data/PostTest.java
Labels: accessibility, backend, frontend, testing

#102 Fix small bugs with smart time filling and index page map
  src/main/webapp/assets/js/feedScript.js
  src/main/webapp/assets/js/indexScript.js
Labels: bug

#100 Changes Setup of Datastore
  src/main/java/com/google/sps/data/Post.java
  src/main/java/com/google/sps/servlets/PostDataServlet.java
  src/main/webapp/WEB-INF/datastore-indexes.xml
  src/test/java/com/google/sps/data/PostTest.java
Labels: backend, enhancement, refactor
