Repository googleinterns/noms, pull requests merged in 2020-07, with the labels that each got.

#2 Add Information to README.md
  README.md
Labels: documentation

#4 Setup of Relevant Pages
  .github/workflows/javaformat.yml
  README.md
  src/main/java/com/google/sps/data/User.java
  src/main/webapp/about.html
  src/main/webapp/assets/script.js
  src/main/webapp/assets/style.css
  src/main/webapp/contact.html
  src/main/webapp/find-events.html
  src/main/webapp/index.html
  src/main/webapp/map.html
  src/main/webapp/sign-up.html
  src/main/webapp/style.css
Labels: documentation, enhancement, prototype

#7 Adds Feed Page and Button Prototype
  src/main/webapp/feed.html
  src/main/webapp/feedStyle.css
Labels: prototype

#8 Create LICENSE
  LICENSE
Labels: documentation

#10 Add Basic Sign-Up Prototype
  src/main/java/com/google/sps/data/User.java
  src/main/java/com/google/sps/servlets/UserDataServlet.java
  src/main/webapp/assets/style.css
  src/main/webapp/sign-up.html
Labels: enhancement, prototype

#9 Add location translator and secrets management
  pom.xml
  src/main/java/com/google/sps/servlets/SecretsManagerServlet.java
  src/main/java/com/google/sps/servlets/TranslateLocationServlet.java
  src/main/webapp/assets/script.js
Labels: enhancement

#11 Adds Post Prototypes to Find Events Page
  src/main/webapp/assets/feedStyle.css
  src/main/webapp/assets/script.js
  src/main/webapp/feed.html
  src/main/webapp/feedStyle.css
  src/main/webapp/find-events.html
Labels: prototype

#12 Add dynamic marker sizing, coloring, and fading
  .github/workflows/calibreapp-image-actions.yml
  src/main/webapp/about.html
  src/main/webapp/assets/feedScript.js
  src/main/webapp/assets/feedStyle.css
  src/main/webapp/assets/greymarker.svg
  src/main/webapp/assets/mainScript.js
  src/main/webapp/assets/mainStyle.css
  src/main/webapp/assets/redmarker.svg
  src/main/webapp/contact.html
  src/main/webapp/find-events.html
  src/main/webapp/index.html
Labels: enhancement

#14 Add Email as Primary Key
  pom.xml
  src/main/java/com/google/sps/data/User.java
  src/main/java/com/google/sps/servlets/UserDataServlet.java
  src/main/webapp/assets/feedStyle.css
  src/main/webapp/assets/mainStyle.css
  src/main/webapp/find-events.html
  src/main/webapp/sign-up.html
Labels: frontend, prototype

#17 Add click functionality to map markers
  src/main/webapp/assets/feedScript.js
  src/main/webapp/assets/feedStyle.css
Labels: enhancement, frontend

#19 Add landing page and multi-college support
  src/main/webapp/about.html
  src/main/webapp/assets/bobaemoji.svg
  src/main/webapp/assets/burgeremoji.svg
  src/main/webapp/assets/college-locations.json
  src/main/webapp/assets/feedScript.js
  src/main/webapp/assets/indexScript.js
  src/main/webapp/assets/indexStyle.css
  src/main/webapp/assets/mainStyle.css
  src/main/webapp/assets/pizzaemoji.svg
  src/main/webapp/assets/spoofmap.svg
  src/main/webapp/contact.html
  src/main/webapp/find-events.html
  src/main/webapp/index.html
  src/main/webapp/sign-up.html
Labels: backend, enhancement, frontend

#20 Adds the "Create Post" Modal
  src/main/webapp/assets/feedScript.js
  src/main/webapp/assets/feedStyle.css
  src/main/webapp/find-events.html
Labels: frontend, prototype
